### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by aliceinpalth** [Moolt/LevelGenerator#1]
@Moolt I was playing around with this and absolutely love it. Is there any chance of a code license being developed? I'd love to know if I can work based off of this for my own Unity game.

**Comment by Moolt** [comment]
Hi, I'm happy to hear that you enjoy my plug in and sorry for answering so late.
The code doesn't apply to any specific license but you have my permission to use it in your project (also commercially) and modify it to your needs. It's up to you whether your want to credit me.

**Comment by aliceinpalth** [comment]
Thanks for getting back to me! I'll definitely be playing around with this.
