### ISSUE TITLE
Constraint Absolute Amount and Start Room do not work.

### ISSUE THREAD

**Issue by VoidFletcher** [Moolt/LevelGenerator#5]
Hello again, Moolt!

When setting up a constraint for absolute room spawn amounts, the level generator seems to ignore the constraint. I have tried setting it up like the image below:
![image](https://user-images.githubusercontent.com/10835605/45039908-f6e1a000-b064-11e8-8d27-7e97f42d98fe.png)

As well as tried setting up the room as a "Start" room, as well as a combination of both. In all cases more than 1 instance of the room is generated.

Is there something that I am doing wrong? :)

**Comment by Moolt** [comment]
This should work. I can only think of the tag being misspelled or missing from the chunk you want to constraint. Is "Spawn" showing up when you click on the plus icon?

**Comment by VoidFletcher** [comment]
I eventually figured out my problem, the chunk in question had two user defined tags, "Barracks" and "Spawn", my guess is it would spawn the initial 1 instance of "Spawn" but then use it again as "Barracks".

Which in essence is still a bug, as having the level generator constrain it to only 1 instance of "Spawn" should force the generation to only include a single instance of "Spawn", however, this is not as critical as it first seemed, and I can work around it.

Also could you explain how "Start" and "End" rooms work? I'm struggling to find their purpose, I would assume having a start room forces only 1 start room to be chosen. Perhaps it does, I haven't tested it yet after removing the user defined tag "Barracks".

Thanks moolt! Hope you're doing well.

**Comment by Moolt** [comment]
This sounds like a bug, yes. I guess I never thought about it. If you found a workaround for now, that's great.

This is kind of a low level thing. First, a graph is being created depending on your input parameters - like in the image. It will then be replaced with actual chunk instances. (Green = start, red = end, blue = between start and end, yellow = side rooms).

![level graph](https://user-images.githubusercontent.com/5003354/45114388-29ff5e80-b14d-11e8-9a4c-66cceba7d1a3.png)

Then these rooms are filled with actual chunks depending on the constraints you've set.

You are right - there is always only one start and only one end room. But if you set the target to ``Start Room`` and the tag to ``Spawn``, this will only guarantee that the start room will be instantiated as a chunk containing the tag ``Spawn``. It will not limit the overall usage of spawn. As you mentioned in your first post, you'd need two constraints for that.

![spawn](https://user-images.githubusercontent.com/5003354/45114814-4fd93300-b14e-11e8-8b6f-65c54e3d7538.PNG)

Edit: The idea behind this level graph is, that you can set a minimal distance between your starting and ending room, so you don't spawn directly next to the end.

**Comment by VoidFletcher** [comment]
Ahhh I see that makes sense! So I suppose it isn't completely a bug, it's just depending on how you set it up. So feel free to mark this issue as closed if you feel it is working as intended. 

Thanks again :D
