### ISSUE TITLE
Level generation is not using the most efficient masks during hallway generation.

### ISSUE THREAD

**Issue by VoidFletcher** [Moolt/LevelGenerator#6]
Good evening, Moolt!

So this is a bit of a random issue, took me a few generations to get it to pop up.
![image](https://user-images.githubusercontent.com/10835605/45385052-1b62ec80-b610-11e8-9dba-1eb7720d240d.png)

When you add a hallway mask with 3 or 4 connections, the level generation starts to use that in "straight" sections and other places where a better match is possible.

So a straight hallway which would require a connection on either end, may end up using a mask with 3 or even 4 connections in the mask. 

Say a corner, may even use a mask with 4 open connections.

Like such:
![image](https://user-images.githubusercontent.com/10835605/45385278-9e844280-b610-11e8-929e-b09973346e8b.png)

Instead, the hallway masks should be matched to fit in with the most exact matches possible.

**Comment by Moolt** [comment]
It's super hard talking about masks when I don't see a screenshot of each of them.
Also I don't consider this a bug, it was never my intention of prioritizing masks depending on how good they fit and I won't add such feature in the near future if ever.

You can, however, manually prioritize masks with constraints by using values > 0.5. This might already fix the problems you're having. 

![constraint](https://user-images.githubusercontent.com/5003354/45388362-0b9bd600-b619-11e8-977a-2d9aacb72ae3.PNG)
